export { Login } from './login'
export { Cadastro } from './cadastro'
export { CadastroCurriculo } from './cadastro-curriculo'
export { Curriculo } from './curriculo'
export { Vagas } from './vagas'
export { Processos } from './processos'
export { ProcessosVaga } from './processos-vaga'